### 1 What does Pandas stand for?
#### Pandas stands for either Panal Data or Python Data Analytics

### 2 What are the 2 collections used in Pandas?
#### Series and Dataframe

### 3 Name 4 things Pandas can do for us.
#### Pandas can manipulate, prepare, model, and analyze data

### 4 To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
#### df.sort_values()

### 5 What is a CSV?
#### A .CSV is a file type has comma seperated values in it.

### 6 When cleaning data what values do we not like in our data?
#### We do not like Null or NaN values.

In [17]:
## #7 Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()


import numpy as np

array1 = np.array([[2,4,],[6,8],[10,12],[1,3],[5,7],[9,11]])
RSarray1 = array1.reshape(2,3,2)
print(np.shape(RSarray1))

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[ 1  3]
  [ 5  7]
  [ 9 11]]]
(2, 3, 2)


In [20]:
## #8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
array2 = np.linspace(0,20, 6)
print(array2)

[ 0.  4.  8. 12. 16. 20.]


In [25]:
## #9 Make a Deep Copy of the above array
import copy
array2C1 = copy.deepcopy(array2)
print(array2C1)


[ 0.  4.  8. 12. 16. 20.]


In [31]:
## #10 Concatenate these 3 arrays into a new array named 'newArray'...
array3 = ([[25, 16]])
array4 = ([[11, 2], [13, 4]])
array5 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array3, array4, array5), 0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [32]:
## #11 Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [35]:
## #12 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
[[[ a,  b],[ c , d],[e ,f]],[[ g,  h],[ i,  j],[ k, l]]] = RSarray1
upv1 = a,c,e
upv2 = b,d,f
upv3 = g,i,k
upv4 = h,j,l
print(upv1)
print(upv2)
print(upv3)
print(upv4)

(2, 6, 10)
(4, 8, 12)
(1, 5, 9)
(3, 7, 11)


In [36]:
## #13 Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

newArray2 = np.concatenate((one, two, three), 0)
comboArray = np.sort(newArray2)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [69]:
## 14 Take 'comboArray' and perform the following slicing activities:

## print sec1 - the 2nd element
## print sec2 - all elements from the 3rd element to the last
## print sec3 - all elements from the 4th to the 14th elements
## print sec4 - the last 6 elements
## print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
## print sec6 - from #20 every even element to the end
## print sec7 - from the last element moving forward, every 5th element.

print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:13])
print(comboArray[-6:])
print(comboArray[-28:-10])
print(comboArray[16::2])
print(comboArray[-28::5])

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[ 0  5 12 17 24]


In [75]:
## #15 Using Series, create a DataFrame that looks like this:
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = "Ingredients")
Quantity = pd.Series([4,1,2,1], name = "Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name = "Unit")

df1 = pd.concat([Ingredients, Quantity, Unit], axis=1)
print(df1)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [76]:
## #16 Take this data and create a DataFrame named studentData
SD1 = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(SD1)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [80]:
## #17 Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
desserts1 = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData= studentData.assign(Desserts = desserts1)

print(studentData)


      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [83]:
## #18 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name","address"], inplace=True, ascending=True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [84]:
## #19 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cows_and_goats.csv")

In [90]:
## #20 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

VeggieInfo = {'Name': ['Celery', 'Carrots', 'Onions', 'Squash', 'Cabbage'],
        'Size': [2, 2, 1, 3, 4],
        'Color': ['green', 'orange', 'yellow', 'yellow', 'green'],
        'Growth_Speed': [4, 2, 2, 1, 2],
       }
Vegetables = pd.DataFrame(VeggieInfo)
Vegetables.to_csv("VeggieTable")

tasteRating = ["bitter", "sweet", "sour", "mellow", "sour"]
Vegetables = Vegetables.assign(Taste_Rating = tasteRating)
print(Vegetables)

Vegetables.to_csv("NewVeggieTable")

      Name  Size   Color  Growth_Speed Taste_Rating
0   Celery     2   green             4       bitter
1  Carrots     2  orange             2        sweet
2   Onions     1  yellow             2         sour
3   Squash     3  yellow             1       mellow
4  Cabbage     4   green             2         sour
